version: '3.1'

services:
  db:
    image: postgres:11
    environment:
      PGHOST: localhost
      PGPORT: '5432'
      PGUSER: postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    
