version: '3.1'

services:
  db:
    image: postgres:11
    environment:
      PGHOST: localhost
      PGPORT: '5432'
      PGDATABASE: packet_invoice_test
      PGUSER: postgres
    ports:
      - "5432:5432"
    volumes:
    - ./postgres:/var/lib/postgresql/data
    